---
title: "About RERITE"
---

We are a group of volunteers who are passionate about practicing and promoting Reproducible Research (RR) in Transportation Engineering. View our hands-on **tutorial** [here](https://www.rerite.org/itsc24-rr-tutorial/). 

## Vision and Mission

### Vision

*A transportation community where open science, reproducible research and replicable studies are the norms, advancing scientific rigour, accelerating innovation and fostering translation into practice.*

The RERITE Working Group envisions a future in which **every study** in **transportation engineering** is **fully openly available**, **reproducible** and **replicable**. Demonstrating the reproducibility of research findings not only shows scientific integrity but also "inspires trust and respect, and encourages reuse", yielding a more efficient, robust and impactful research ecosystem ([The Official PLOS Blog, 2022](https://theplosblog.plos.org/2022/07/reproducibility/#:~:text=Demonstrating%20reproducibility%20shows%20integrity%2C%20inspires,the%20reproducibility%20of%20your%20research)). By embedding reproducibility into the research process, RERITE strives to accelerate innovation in transportation, attract top talent to the field, and justify research investments. Thanks to these efforts, transportation agencies, industry, and the public will more confidently rely on research findings to inform critical decisions, knowing the underlying data and methods have been reproduced and replicated by peers. 

### Mission

*To advance reproducible research practices in transportation engineering by promoting open science principles, developing best practices, and fostering community engagement.*

The core mission of the RERITE Working Group is to **champion openness**, **transparency** and **rigour** in **transportation research**. This mission involves (1) raising awareness regarding the importance of reproducibility, (2) providing training and resources to support data and code sharing, and (3) collaborating with key stakeholders to remove barriers to transparency. RERITE strongly believes that "transparency is superior to trust" ([Munafo et al., 2017](https://www.nature.com/articles/s41562-016-0021)) - all supporting data, methods, and codes should be openly available so that results can be independently verified. By doing so, we can ensure research funded by public or private investment yields full credibility ([Wood and Schalkwyk, 2025](https://www.scirp.org/journal/paperinformation?paperid=140233#:~:text=troubling%20for%20many%20reasons%20particularly,20)). In summary, RERITE aims to foster a cultural shift towards fully integrating open science principles – open data and tools, rigorous methods, reproducible and replicable findings – into transportation engineering research for the long term.
