---
title: "Team"
---

## Steering Committee

- **Chair**  
  Dr. Cathy Wu  
  *Massachusetts Institute of Technology (MIT)*

- **Vice-Chair and Major Event Coordinators**  
  Dr. Xuesong (Simon) Zhou  
  *Arizona State University*  
  Dr. Bidisha Ghosh  
  *Trinity College Dublin*

- **Communication Officers (Joint)**  
  Dr. Silvia Francesca Varotto  
  Dr. Bahman Madadi  
  *École Nationale des Travaux Publics de l'État, LICIT-ECO7*

- **Junior Researcher Engagement Officer**  
  Zhe Fu  
  *University of California, Berkeley*

- **Secretary**  
  Dr. Michail Makridis  
  *ETH Zürich*

## Members

- Mostafa Ameli, Université Gustave Eiffel: Volunteer researcher
- Linda Belkessac, Université Gustave Eiffel: Volunteer researcher
- Yongqi Dong, Delft University of Technology: Volunteer researcher
- Junyi Ji, Vanderbilt University: Volunteer researcher
- Ruth Lu, Massachusetts Institute of Technology: Volunteer researcher
- Gregory S. Macfarlane, Brigham Young University: Volunteer researcher
- Nicolas Saunier, Polytechnique Montréal: Volunteer researcher
- Liming Wang, Portland State University: Volunteer researcher